/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package my.ISUProject;

import java.util.Scanner;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.io.EOFException;
import java.security.NoSuchAlgorithmException;
import java.util.NoSuchElementException;
import java.util.StringTokenizer;
import java.util.ArrayList;
import java.util.HashSet;
import java.util.Set;
import javax.swing.DefaultComboBoxModel;
import org.jdesktop.swingx.autocomplete.AutoCompleteDecorator;

/**
 *
 * @author 335550752
 */
public class Main extends javax.swing.JFrame {

    File playerData = new File("playerData.txt");
    File teams = new File("teams.txt");
    ArrayList<String> playerStats = new ArrayList<>();
    ArrayList<String> players = new ArrayList<>();
    ArrayList<String> playersAvailable = new ArrayList<>();
    ArrayList<String> teamList = new ArrayList<>();
    ArrayList<String> sortNames = new ArrayList<>();
    ArrayList<Double> sortPoints = new ArrayList<>();
    Team team = new Team();

    /**
     * Creates new form ISUProjectUI
     */
    public Main() {
        initComponents();
        updateTeams();
        AutoCompleteDecorator.decorate(playersCombo);
        AutoCompleteDecorator.decorate(deleteCombo);
        AutoCompleteDecorator.decorate(editCombo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        playerList = new javax.swing.JList();
        playersCombo = new javax.swing.JComboBox();
        tradeBtn = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        toTradeCombo = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        searchField = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        searchList1 = new javax.swing.JList();
        jScrollPane2 = new javax.swing.JScrollPane();
        sortedList = new javax.swing.JList();
        jLabel6 = new javax.swing.JLabel();
        teamField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        positionField = new javax.swing.JTextField();
        pointsField = new javax.swing.JTextField();
        reboundsField = new javax.swing.JTextField();
        assistsField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        addPlayer = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        deleteBtn = new javax.swing.JButton();
        deleteCombo = new javax.swing.JComboBox();
        jLabel15 = new javax.swing.JLabel();
        editCombo = new javax.swing.JComboBox();
        sortByPoints = new javax.swing.JButton();
        sortByName = new javax.swing.JButton();
        teamCombo = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        teamEdit = new javax.swing.JTextField();
        nameEdit = new javax.swing.JTextField();
        positionEdit = new javax.swing.JTextField();
        pointsEdit = new javax.swing.JTextField();
        reboundsEdit = new javax.swing.JTextField();
        assistsEdit = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        editBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrollPane1.setViewportView(playerList);

        playersCombo.setEditable(true);

        tradeBtn.setText("Trade");
        tradeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tradeBtnActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");

        jLabel5.setText("Your Players");

        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(searchList1);

        jScrollPane2.setViewportView(sortedList);

        jLabel6.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel6.setText("Add Player");

        jLabel8.setText("Team");

        jLabel9.setText("Name");

        jLabel10.setText("Position");

        jLabel11.setText("Points");

        jLabel12.setText("Rebounds");

        jLabel13.setText("Assists");

        addPlayer.setText("Add");
        addPlayer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPlayerActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel14.setText("Delete Player");

        deleteBtn.setText("Delete");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel15.setText("Edit Player");

        editCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editComboActionPerformed(evt);
            }
        });

        sortByPoints.setText("Sort By Points ↑");
        sortByPoints.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByPointsActionPerformed(evt);
            }
        });

        sortByName.setText("Sort By Name ↑");
        sortByName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sortByNameActionPerformed(evt);
            }
        });

        teamCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                teamComboActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel2.setText("Select a team");

        jLabel1.setBackground(new java.awt.Color(153, 204, 255));
        jLabel1.setFont(new java.awt.Font("Cambria", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(50, 0, 0));
        jLabel1.setText(" Sports Management App");
        jLabel1.setOpaque(true);

        jLabel16.setFont(new java.awt.Font("Cambria", 0, 14)); // NOI18N
        jLabel16.setText("Search By Team or Position");

        editBtn.setText("Edit");
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(teamField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(positionField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pointsField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(reboundsField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(assistsField, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(addPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(reboundsEdit, javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel15, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(pointsEdit)
                                            .addComponent(assistsEdit))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(editCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(positionEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                                        .addComponent(nameEdit, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(teamEdit, javax.swing.GroupLayout.Alignment.LEADING)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(deleteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(0, 0, Short.MAX_VALUE)
                                            .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(editBtn)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(teamCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(16, 16, 16)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tradeBtn)
                                        .addGap(29, 29, 29)
                                        .addComponent(jButton2))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(toTradeCombo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(playersCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(65, 65, 65)
                                .addComponent(jLabel5)))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(sortByName)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(sortByPoints)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sortByPoints)
                                .addComponent(sortByName)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(teamCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(playersCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(toTradeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(4, 4, 4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tradeBtn)
                            .addComponent(jButton2))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 49, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jLabel14)
                    .addComponent(jLabel6)
                    .addComponent(editCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(teamEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(teamField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(deleteBtn)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(nameEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(positionField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(positionEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pointsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11)
                            .addComponent(pointsEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(reboundsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(reboundsEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(assistsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(assistsEdit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addPlayer)
                    .addComponent(editBtn))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tradeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tradeBtnActionPerformed
        String player1 = playersCombo.getSelectedItem().toString();
        String player2 = toTradeCombo.getSelectedItem().toString();
        String replace1, replace2, team1;

        for (int i = 0; i < playerStats.size(); i++) {
            if (playerStats.get(i).contains(player1)) {
                String[] split = playerStats.get(i).split(";");
                team1 = split[0];
                replace1 = playerStats.get(i).replace(team1, team.getTeam());
                playerStats.set(i, replace1);

                for (int j = 0; j < playerStats.size(); j++) {
                    if (playerStats.get(j).contains(player2)) {
                        replace2 = playerStats.get(j).replace(team.getTeam(), team1);
                        playerStats.set(j, replace2);
                    }
                }
            }
        }
        try { //print out the user data again, updating the user which wanted to swtich password. 
            PrintWriter output = new PrintWriter(playerData);
            for (String playerStats1 : playerStats) {
                output.println(playerStats1);
            }
            output.close();
        } catch (FileNotFoundException ex) {
            System.out.printf("ERROR %s\n", ex);
        }
        updateTeamList();
    }//GEN-LAST:event_tradeBtnActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        searchList1.removeAll();
        ArrayList<String> error = new ArrayList<>();
        error.add("Error:");
        error.add("Please enter a position");
        String search = searchField.getText();
        ArrayList<String> player1 = new ArrayList<>();
        if (search.equals("Guard") || search.equals("Forward") || search.equals("Center")) {
            for (int i = 0; i < playerStats.size(); i++) {
                if (playerStats.get(i).contains(search)) {
                    String[] split = playerStats.get(i).split(";");
                    player1.add(split[1]);
                    searchList1.setModel(new javax.swing.AbstractListModel() {
                        ArrayList<String> strings = player1;

                        @Override
                        public int getSize() {
                            return strings.size();
                        }

                        @Override
                        public Object getElementAt(int i) {
                            return strings.get(i);
                        }
                    });
                }
            }
        } else {
            searchList1.setModel(new javax.swing.AbstractListModel() {
                ArrayList<String> strings = error;

                @Override
                public int getSize() {
                    return strings.size();
                }

                @Override
                public Object getElementAt(int i) {
                    return strings.get(i);
                }
            });
        }
    }//GEN-LAST:event_searchFieldActionPerformed

    private void addPlayerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPlayerActionPerformed
        Player player = new Player();
        player.setTeam(teamField.getText());
        player.setName(nameField.getText());
        player.setPosition(positionField.getText());
        player.setPoints(pointsField.getText());
        player.setRebounds(reboundsField.getText());
        player.setAssists(assistsField.getText());
        player.createPlayer();
        updateTeams();
        teamField.setText(null);
        nameField.setText(null);
        positionField.setText(null);
        pointsField.setText(null);
        reboundsField.setText(null);
        assistsField.setText(null);
    }//GEN-LAST:event_addPlayerActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        String delete = deleteCombo.getSelectedItem().toString();
        for (int i = 0; i < playerStats.size(); i++) {
            if (playerStats.get(i).contains(delete)) {
                playerStats.remove(i);
            }
        }

        try {
            PrintWriter output = new PrintWriter(playerData);
            output.print("");
            for (String playerStat : playerStats) {
                output.println(playerStat);
            }
            output.close();
        } catch (FileNotFoundException ex) {
            System.out.printf("ERROR %s\n", ex);
        }

        updateTeams();
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void sortByPointsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByPointsActionPerformed
        sortedList.removeAll();
        sortPoints.clear();
        ArrayList<String> sorted = new ArrayList<>();
        for (String playerStat : playerStats) {
            String[] split = playerStat.split(";");
            double temp = Double.parseDouble(split[3]);
            
            sortPoints.add(temp);
        }

        if (sortByPoints.getText().contains("↓")) {
            sortPoints = sortPointsAscending(sortPoints);
            sortByPoints.setText("Sort By Points ↑");
        } else {
            sortPoints = sortPointsDescending(sortPoints);
            sortByPoints.setText("Sort By Points ↓");
        }
        for (int i = 0; i < sortPoints.size(); i++) {
            sorted.add(Double.toString(sortPoints.get(i)));
        }
        for (int i = 0; i < sorted.size(); i++) {
            for (int j = 0; j < players.size(); j++) {
                if (players.get(j).contains(sorted.get(i))) {
                    sorted.set(i, "gay");
                }
            }
            
        }
        System.out.println(sorted);
        sorted.set(5, "gay");
        sortedList.setModel(new javax.swing.AbstractListModel() {
            ArrayList<String> strings = sorted;

            @Override
            public int getSize() {
                return strings.size();
            }

            @Override
            public Object getElementAt(int i) {
                return strings.get(i);
            }
        });
    }//GEN-LAST:event_sortByPointsActionPerformed

    private void sortByNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sortByNameActionPerformed
        sortedList.removeAll();
        sortNames.clear();
        for (String playerStat : playerStats) {
            String[] split = playerStat.split(";");
            sortNames.add(split[1]);
        }

        if (sortByName.getText().contains("↓")) {
            sortNames = sortStringAscending(sortNames);
            sortByName.setText("Sort By Name ↑");
        } else {
            sortNames = sortStringDescending(sortNames);
            sortByName.setText("Sort By Name ↓");
        }

        sortedList.setModel(new javax.swing.AbstractListModel() {
            ArrayList<String> strings = sortNames;

            @Override
            public int getSize() {
                return strings.size();
            }

            @Override
            public Object getElementAt(int i) {
                return strings.get(i);
            }
        });
    }//GEN-LAST:event_sortByNameActionPerformed

    private void teamComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_teamComboActionPerformed
        team.clearPlayers();
        playerList.removeAll();
        String teamStr = teamCombo.getSelectedItem().toString();
        team.setTeam(teamStr);
        team.setPlayersOnly();
        team.setStats();
        toTradeCombo.setModel(new DefaultComboBoxModel(team.getPlayersOnly().toArray()));
        playerList.setModel(new javax.swing.AbstractListModel() {
            ArrayList<String> strings = team.getPlayersOnly();

            @Override
            public int getSize() {
                return strings.size();
            }

            @Override
            public Object getElementAt(int i) {
                return strings.get(i);
            }
        });

        for (String playerStat : playerStats) {
            if (!playerStat.contains(team.getTeam())) {
                String[] split = playerStat.split(";");
                String player = split[1];
                playersAvailable.add(player);
            }
        }
        playersCombo.setModel(new DefaultComboBoxModel(playersAvailable.toArray()));
        getContentPane().add(playersCombo);
    }//GEN-LAST:event_teamComboActionPerformed

    private void editComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editComboActionPerformed
        String player = editCombo.getSelectedItem().toString();
        String editPlayer;
        for (String playerStat : playerStats) {
            if (playerStat.contains(player)) {
                editPlayer = playerStat;
                String[] split = editPlayer.split(";");
                teamEdit.setText(split[0]);
                nameEdit.setText(split[1]);
                positionEdit.setText(split[2]);
                pointsEdit.setText(split[3]);
                reboundsEdit.setText(split[4]);
                assistsEdit.setText(split[5]);
            }
        }
    }//GEN-LAST:event_editComboActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        for (int i = 0; i < playerStats.size(); i++) {
            if (playerStats.get(i).contains(nameEdit.getText())) {
                playerStats.remove(i);
                playerStats.add(teamEdit.getText() + ";" + nameEdit.getText() + ";"
                        + positionEdit.getText() + ";" + pointsEdit.getText() + ";"
                        + reboundsEdit.getText() + ";" + assistsEdit.getText());
            }
        }
        try {
            PrintWriter output = new PrintWriter(playerData);
            output.print("");
            for (String playerStat : playerStats) {
                output.println(playerStat);
            }
            output.close();
        } catch (FileNotFoundException ex) {
            System.out.printf("ERROR %s\n", ex);
        }
        updateTeams();
        teamEdit.setText(null);
        nameEdit.setText(null);
        positionEdit.setText(null);
        pointsEdit.setText(null);
        reboundsEdit.setText(null);
        assistsEdit.setText(null);
    }//GEN-LAST:event_editBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    public void updateTeamList() {
        playersAvailable.clear();
        team.clearPlayers();
        team.setPlayers();
        team.setPlayersOnly();
        playerList.removeAll();

        toTradeCombo.setModel(new DefaultComboBoxModel(team.getPlayersOnly().toArray()));
        playerList.setModel(new javax.swing.AbstractListModel() {
            ArrayList<String> strings = team.getPlayersOnly();

            @Override
            public int getSize() {
                return strings.size();
            }

            @Override
            public Object getElementAt(int i) {
                return strings.get(i);
            }
        });
        for (String playerStat : playerStats) {
            if (!playerStat.contains(team.getTeam())) {
                String[] split = playerStat.split(";");
                String player = split[1];
                playersAvailable.add(player);
            }
        }
        playersCombo.setModel(new DefaultComboBoxModel(playersAvailable.toArray()));
    }

    private void updateTeams() {
        playerStats.clear();
        teamList.clear();
        players.clear();
        try {
            Scanner sc = new Scanner(teams);
            while (sc.hasNextLine()) {
                teamList.add(sc.nextLine());
            }
            Scanner sc2 = new Scanner(playerData);
            while (sc2.hasNextLine()) {
                playerStats.add(sc2.nextLine());
            }
            sc.close();
        } catch (FileNotFoundException ex) {
            Logger.getLogger(Main.class.getName()).log(Level.SEVERE, null, ex);
        }
        teamCombo.setModel(new DefaultComboBoxModel(teamList.toArray()));
        for (String playerStat : playerStats) {
            String[] split = playerStat.split(";");
            players.add(split[1]);
        }
        sortedList.setModel(new javax.swing.AbstractListModel() {
            ArrayList<String> strings = players;

            @Override
            public int getSize() {
                return strings.size();
            }

            @Override
            public Object getElementAt(int i) {
                return strings.get(i);
            }
        });
        deleteCombo.setModel(new DefaultComboBoxModel(players.toArray()));
        editCombo.setModel(new DefaultComboBoxModel(players.toArray()));
    }

    public static ArrayList sortStringAscending(ArrayList<String> listIn) {
        for (int i = 0; i < listIn.size(); i++) { //repeat for list size
            int index = i; //set index to i
            for (int j = i + 1; j < listIn.size(); j++) {
                if (listIn.get(j).compareTo(listIn.get(index)) < 0) { //if list at j is less than list at index, make a swap
                    index = j; //searching for lowest index  
                }
            }
            if (index != i) { //if index does not equal to i, swap the list item at i with the item at index
                String temp = listIn.get(index);
                listIn.set(index, listIn.get(i));
                listIn.set(i, temp);
            }
        }
        return listIn;
    }

    public static ArrayList sortStringDescending(ArrayList<String> listIn) {
        for (int i = 0; i < listIn.size(); i++) { //repeat for list size
            int index = i; //set index to i
            for (int j = i + 1; j < listIn.size(); j++) {
                if (listIn.get(j).compareTo(listIn.get(index)) > 0) { //if list at j is less than list at index, make a swap
                    index = j; //searching for lowest index  
                }
            }
            if (index != i) { //if index does not equal to i, swap the list item at i with the item at index
                String temp = listIn.get(index);
                listIn.set(index, listIn.get(i));
                listIn.set(i, temp);
            }
        }
        return listIn;
    }

    public static ArrayList sortPointsAscending(ArrayList<Double> listIn) {
        for (int i = 0; i < listIn.size(); i++) { //repeat for list size
            int index = i; //set index to i
            for (int j = i + 1; j < listIn.size(); j++) {
                if (listIn.get(j) < listIn.get(index)) { //if list at j is less than list at index, make a swap
                    index = j; //searching for lowest index  
                }
            }
            if (index != i) { //if index does not equal to i, swap the list item at i with the item at index
                double temp = listIn.get(index);
                listIn.set(index, listIn.get(i));
                listIn.set(i, temp);
            }
        }
        return listIn;
    }

    public static ArrayList sortPointsDescending(ArrayList<Double> listIn) {
        for (int i = 0; i < listIn.size(); i++) { //repeat for list size
            int index = i; //set index to i
            for (int j = i + 1; j < listIn.size(); j++) {
                if (listIn.get(j) > listIn.get(index)) { //if list at j is less than list at index, make a swap
                    index = j; //searching for lowest index  
                }
            }
            if (index != i) { //if index does not equal to i, swap the list item at i with the item at index
                double temp = listIn.get(index);
                listIn.set(index, listIn.get(i));
                listIn.set(i, temp);
            }
        }
        return listIn;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addPlayer;
    private javax.swing.JTextField assistsEdit;
    private javax.swing.JTextField assistsField;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JComboBox deleteCombo;
    private javax.swing.JButton editBtn;
    private javax.swing.JComboBox editCombo;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField nameEdit;
    private javax.swing.JTextField nameField;
    private javax.swing.JList playerList;
    private javax.swing.JComboBox playersCombo;
    private javax.swing.JTextField pointsEdit;
    private javax.swing.JTextField pointsField;
    private javax.swing.JTextField positionEdit;
    private javax.swing.JTextField positionField;
    private javax.swing.JTextField reboundsEdit;
    private javax.swing.JTextField reboundsField;
    private javax.swing.JTextField searchField;
    private javax.swing.JList searchList1;
    private javax.swing.JButton sortByName;
    private javax.swing.JButton sortByPoints;
    private javax.swing.JList sortedList;
    private javax.swing.JComboBox teamCombo;
    private javax.swing.JTextField teamEdit;
    private javax.swing.JTextField teamField;
    private javax.swing.JComboBox toTradeCombo;
    private javax.swing.JButton tradeBtn;
    // End of variables declaration//GEN-END:variables
}
